### ISSUE TITLE
Can't upload WebP images

### ISSUE THREAD

**Issue by hibobmaster** [AlfredoRamos/phpbb-ext-imgur#163]
Upload webp image get following error:

```
Request to: /3/image failed with: "File type invalid (1)"
```

version: 1.7.2
sample image:  https://down.sky-and-poem.fun/source/static/Colors%20of%20our%20Spring.webp

**Comment by AlfredoRamos** [comment]
The API does not support uploading WebP images, so it has been removed from the allowed list.
