### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Hartenheer** [AlfredoRamos/phpbb-ext-imgur#7]
I recently used topic locked with Move Topics When Locked.
Now I get this below error message every day
What can I do to solve this?

Een algemene fout is opgetreden: General Error 
» SQL ERROR [ mysqli ]

[0]

SQL

No values specified for SQL IN comparison

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 996
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 547
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 441
CALL: phpbb\db\driver\driver->sql_in_set()

FILE: [ROOT]/ext/alfredoramos/autolocktopics/includes/helper.php
LINE: 241
CALL: phpbb\db\driver\factory->sql_in_set()

FILE: [ROOT]/ext/alfredoramos/autolocktopics/includes/helper.php

LINE: 131
CALL: alfredoramos\autolocktopics\includes\helper->lock_topics()

FILE: [ROOT]/ext/alfredoramos/autolocktopics/cron/task/auto_lock_topics.php
LINE: 52
CALL: alfredoramos\autolocktopics\includes\helper->auto_lock()

FILE: (not given by php)
LINE: (not given by php)
CALL: alfredoramos\autolocktopics\cron\task\auto_lock_topics->run()

FILE: [ROOT]/phpbb/cron/task/wrapper.php
LINE: 104
CALL: call_user_func_array()

FILE: [ROOT]/cron.php
LINE: 78
CALL: phpbb\cron\task\wrapper->__call()

**Comment by AlfredoRamos** [comment]
Please, open a new issue in the appropiate repository, this is for the Imgur uploader extension.
