### ISSUE TITLE
Field filters make album ID required in ACP controller

### ISSUE THREAD

**Issue by AlfredoRamos** [AlfredoRamos/phpbb-ext-imgur#9]
Reported originally in the phpBB Imgur extension support seccion:

https://www.phpbb.com/customise/db/extension/imgur/support/topic/202596?p=682771#p682771

**Comment by olalavui** [comment]
If set root album account (don't provive album id) will cannot save.

**Comment by AlfredoRamos** [comment]
Hi @olalavui 

That issue has been fixed however I haven't released a new version, you can apply the fix that I give in the previous link:

<details>

<summary>Click to show solution</summary>

File: `ext/alfredoramos/imgur/controller/acp.php`

Search:

```php
			'imgur_album' => [
				'filter' => FILTER_VALIDATE_REGEXP,
				'options' => [
					'regexp' => '#^[a-zA-Z0-9]{5,10}$#'
				]
			]
```

Replace it with:

```php
			'imgur_album' => [
				'filter' => FILTER_VALIDATE_REGEXP,
				'options' => [
					'regexp' => '#^(?:[a-zA-Z0-9]{5,10})?$#'
				]
			]
```

</details>

https://www.phpbb.com/customise/db/extension/imgur/support/topic/198266?p=685571#p685571
